name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # STAGE 1: CLONE
      - name: Stage 1 - Checkout Code
        uses: actions/checkout@v3

      # STAGE 2: BUILD
      - name: Stage 2 - Build Docker Images
        run: |
          # We hardcode 'kanigai' because the secret was empty
          docker build -t kanigai/smartcampus-frontend:latest ./frontend
          docker build -t kanigai/smartcampus-backend:latest ./backend

      # STAGE 3: CREATE IMAGE & PUSH
      - name: Stage 3 - Login and Push to Docker Hub
        run: |
          # Make sure DOCKER_HUB_TOKEN exists in settings, 
          # otherwise replace ${{ secrets.DOCKER_HUB_TOKEN }} with "16sept2005"
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "kanigai" --password-stdin
          docker push kanigai/smartcampus-frontend:latest
          docker push kanigai/smartcampus-backend:latest